# Generated by Django 3.1.3 on 2020-11-30 13:56

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ImageField(blank=True, null=True, upload_to='post_headers')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=511, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('Health', 'Health'), ('Engineering', 'Engineering'), ('Foundation', 'Foundation'), ('Campaign', 'Campaign'), ('Safety', 'Safety'), ('Policy', 'Policy'), ('Partnership', 'Partnership')], max_length=64)),
                ('featured_status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
