# Generated by Django 3.2 on 2021-04-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plasmadonor',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
