# Generated by Django 3.2 on 2021-05-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bloodrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('Live', 'Live'), ('Closed', 'Closed')], max_length=10)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
